import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import "@uploadthing/react/styles.css";
// import '@ckeditor/ckeditor5-build-classic/build/ckeditor.css';
// or add it to your global CSS file
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
